### PR TITLE
Async, .NET 4.5 and Nearest API implementation

### PR DESCRIPTION
**Pull request by AlistairClark7**

### CODE REVIEW

**Comment by AlistairClark7** [comment]
Not all of the tests pass still, as it seems some data has changed.

**Comment by markembling** [comment]
I've merged this in and also updated some of the test data - you're right, it had changed. I can't really think of a better way than this at the moment, although it could be an ongoing problem. Some package updates are in there too.

**Comment by AlistairClark7** [comment]
Hey, when you get a change could you push the latest version to nuget? Thanks!

**Comment by markembling** [comment]
No worries, it's pushed now. Sorry about that, I'd totally forgotten to do so and have been so busy it just got forgotten. Version 0.0.2 is up now.

**Pull request merged**
